### ISSUE TITLE
Cannot use "//" above "extends" keyword.

### ISSUE THREAD

**Issue by vuminhluan** [DopustimVladimir/atom-pug-autocompile#1]
How can we deal with this problem, sir ?
Because I am not good at English so I can't tell you more detail.
Full error message:
_Declaration of template inheritance ("extends") should be the first thing in the file_
Thanks.

**Comment by nikahmadz** [comment]
I experience the same thing,
unable to use **extends** feature

**Comment by ducnv999** [comment]
I got same problem. This is big issue.
